
ENV["FLASK_APP"] = "flaskr.py"

task :install do
  sh "pip install -r requirements.txt"
end

task :db => :install do
  sh "flask initdb"
end

task :run => :db do
  sh "python flaskr.py"
end

task :uwsgi => :db do
  sh  "uwsgi -p 4 --http :9090 --manage-script-name --mount /=flaskr:app --enable-threads --thunder-lock"
end

task :gunicorn => :db do
  sh "gunicorn flaskr:app --worker-class gevent --workers 4"
end

task :default => :run
